site:
  title: Asset Administration Shell Documentation
  url: https://admin-shell-io.github.io/aas-specs-antora
  start_page: index::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start-paths: .
    - url: https://github.com/admin-shell-io/aas-specs
      branches: IDTA-01001-3-1_working
      start-paths: documentation/IDTA-01001
    - url: https://github.com/rwth-iat/aas-specs-api
      branches: fix/refs
      start-paths: documentation/IDTA-01002-3
    - url: https://github.com/admin-shell-io/aas-specs-iec61360
      branches: IDTA-01003-a-3-1_working
      start-paths: documentation/IDTA-01003-a
    - url: https://github.com/admin-shell-io/aas-specs-aasx
      branches: [IDTA-01005-3-1_working, improve/format]
      start-paths: documentation/IDTA-01005

ui:
  bundle:
    url: https://github.com/admin-shell-io/aas-specs-antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
    
runtime:
  fetch: true
  
antora:
  extensions:
  - '@antora/lunr-extension'
  - '@antora/pdf-extension'

asciidoc:
  attributes:
    xrefstyle: short
