site:
  title: Asset Administration Shell Documentation
  url: https://zrgt.github.io/aas-specs-antora
  start_page: index::index.adoc

content:
  edit_url: '{web_url}/blob/{refname}/{path}'
  sources:
    - url: .
      branches: HEAD
      start-paths: .
    - url: https://github.com/rwth-iat/aas-specs
      branches:
      - IgGa/test_pumls
      start-paths: documentation/IDTA-01001
    - url: https://github.com/admin-shell-io/aas-specs-api
      branches:
      - IDTA-01002-3-0_antora_ref
      - IgGa/integrate_pumls
      start-paths: documentation/IDTA-01002-3
    - url: https://github.com/admin-shell-io/aas-specs-iec61360
      branches:
      - IDTA-01003-a-3-0_antora_ref
      - IDTA-01003-a-3-1_working
      start-paths: documentation/IDTA-01003-a
    - url: https://github.com/admin-shell-io/aas-specs-aasx
      branches:
      - IDTA-01005-3-0_antora_ref
      - IDTA-01005-3-1_working
      start-paths: documentation/IDTA-01005
    - url: https://github.com/rwth-iat/aas-specs-mock
      branches: [master]
      start-paths:
      - 1/documentation/IDTA-02036
      - 2/documentation/IDTA-02036

ui:
  bundle:
    url: https://github.com/admin-shell-io/aas-specs-antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll

runtime:
  fetch: true

antora:
  extensions:
  - '@antora/lunr-extension'
  - '@antora/pdf-extension'

asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    xrefstyle: short
    kroki-server-url: http://localhost:8000
    kroki-fetch-diagram: true
    kroki-plantuml-include: https://raw.githubusercontent.com/rwth-iat/aas-specs/refs/heads/IgGa/test_pumls/documentation/IDTA-01001/modules/ROOT/partials/diagrams/000_theme_conf.puml
